version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_data:/data
      - neo4j_plugins:/plugins
      - neo4j_certificates:/var/lib/neo4j/ssl
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_backups:/var/lib/neo4j/backups
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/${PASSWORD}
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      # - NEO4J_dbms_security_procedures_unrestricted=apoc.,gds.
      # - NEO4J_dbms_security_procedures_whitelist=apoc.,gds.
      # - NEO4J_initial_dbms_default__database=neo4j
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_import_file_use__neo4j__config=true
      # - NEO4J_dbms_memory_heap_initial__size=2G
      # - NEO4J_dbms_memory_pagecache_size=2G
      # - NEO4J_dbms_memory_heap_max__size=2G
      # - NEO4J_PLUGINS=["apoc"]
    ports:
      - 20888:7474
      - 20999:7687
    networks:
      - webproxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.swarm.network=webproxy
        
        # HTTP
        - traefik.http.routers.${TRAEFIK_NAME}-web.rule=Host(`${TRAEFIK_NAME}.dev.thaicloud.ai`)
        - traefik.http.routers.${TRAEFIK_NAME}-web.entrypoints=websecure
        - traefik.http.routers.${TRAEFIK_NAME}-web.tls=true
        - traefik.http.routers.${TRAEFIK_NAME}-web.service=${TRAEFIK_NAME}-web
        - traefik.http.services.${TRAEFIK_NAME}-web.loadbalancer.server.port=7474
      
        # Bolt
        - traefik.tcp.routers.${TRAEFIK_NAME}-bolt.rule=HostSNI(`${TRAEFIK_NAME}bolt.dev.thaicloud.ai`)
        - traefik.tcp.routers.${TRAEFIK_NAME}-bolt.entrypoints=websecure
        - traefik.tcp.routers.${TRAEFIK_NAME}-bolt.tls=true
        - traefik.tcp.services.${TRAEFIK_NAME}-bolt.loadbalancer.server.port=7687
        
volumes:
  neo4j_logs:
  neo4j_conf:
  neo4j_data:
  neo4j_plugins:
  neo4j_import:
  neo4j_backups:
  neo4j_certificates:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.99.201.231,rw,soft,nfsvers=4,nolock,timeo=30
      device: ":/mnt/Swarm/data/neo4j/certificates"

networks:
  webproxy:
    external: true